import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import { builtinModules as builtins } from "node:module";
import { execSync } from "child_process";
import chokidar from "chokidar";
import path from "path";
import fs, { mkdirSync } from "fs";
// Single source of truth for Svelte preprocessing, shared with svelte-check
// (see svelte.config.mjs). Two independent `sveltePreprocess()` calls could
// silently diverge -- svelte-check would then be type-checking a program
// preprocessed differently from what actually ships.
import svelteConfig from "./svelte.config.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Версия берётся из тега и вписывается в manifest.json ниже (updateManifest).
//
// `--always` здесь БЫЛО, и это стоило публичного релиза: при отсутствии тега флаг
// не даёт describe упасть, а возвращает голый sha, который сборка молча вписывает
// в манифест как версию. Так в первый коммит нового репозитория уехало
// "1.1.43-237-g1833d8a" — тег старого репозитория, число коммитов над ним и хеш.
// Никто не соврал: отказ был заранее выключен флагом. Не возвращать.
// Валидатор каталога Obsidian собирает опубликованный архив, в котором .git нет
// вовсе: там describe выходит с кодом 128 и роняет сборку на загрузке модуля.
// Это отдельный случай от «тега нет в git-репозитории» — там падать правильно,
// и строгость ниже сохранена. Здесь же git недоступен как таковой, и источником
// версии становится manifest.json, который архив и так несёт.
const gitTag = (() => {
	try {
		return execSync("git describe --tags", {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch (e) {
		if (fs.existsSync(".git")) throw e; // git есть, тега нет — падаем, как и задумано
		return JSON.parse(fs.readFileSync("manifest.json", "utf8")).version;
	}
})();

// Второй рубеж: describe может вернуть валидную строку неверной ФОРМЫ.
// Аллоулист, а не денилист — перечисляем то, что принимаем, иначе следующая
// неожиданная форма пройдёт молча (голый sha денилист по суффиксу не ловит).
//
// Проверяется только релизная сборка: на ветке describe законно даёт
// "0.0.1-5-gabc1234", и запрет на каждой сборке закрасил бы main следующим же
// коммитом после тега — гейт, запирающий разработку, снимут, а не починят.
const BARE_SEMVER = /^\d+\.\d+\.\d+$/;
if (process.env.CI_COMMIT_TAG && !BARE_SEMVER.test(gitTag)) {
	throw new Error(
		`refusing to build a release: version "${gitTag}" is not a bare semver. ` +
			"Tag the commit being released (git tag X.Y.Z) — the tag IS the version.",
	);
}

const develop = process.argv[2] === "develop";
const staging = process.argv[2] === "staging";
const watch = process.argv[2] === "watch" || staging;
const debug = process.argv[2] === "debug" || watch || staging || develop;
const out = process.argv[3] || ".";
const tld = staging ? "dev" : "md";

// Obsidian vault plugin directory for auto-copy on build
// Только по явной переменной. Здесь стоял личный путь конкретного разработчика:
// публичный репозиторий его нёс, и каждая сборка писала в ту машину.
const obsidianPluginDir = process.env.OBSIDIAN_PLUGIN_DIR || null;

// EVC Team Relay uses relay-onprem mode, no default System 3 URLs.
// (Relay health-check URL is NOT build-time config — it's derived at runtime
// from the relay-onprem settings' per-server controlPlaneUrl; see
// healthUrlForServer() in src/main.ts, TR-26.)
const apiUrl = "";
const authUrl = "";
console.log("git tag:", gitTag);

const NotifyPlugin = {
	name: "on-end",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) execSync(`notify-send "Build Failed"`);
		});
	},
};

const YjsInternalsPlugin = {
	name: "yjs-internals",
	setup(build) {
		build.onResolve({ filter: /^yjs\/dist\/src\/internals$/ }, args => {
			return {
				path: path.resolve("node_modules/yjs/src/internals.js"),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
        "moment",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: true },
			preprocess: svelteConfig.preprocess,
		}),
		YjsInternalsPlugin,
		NotifyPlugin,
	],
	target: "es2018",
	minify: !debug,
	logLevel: "info",
	sourcemap: debug ? "inline" : false,
	define: {
		BUILD_TYPE: debug ? '"debug"' : '"prod"',
		GIT_TAG: `"${gitTag}"`,
		API_URL: `"${apiUrl}"`,
		AUTH_URL: `"${authUrl}"`,
		REPOSITORY: `"entire-vc/evc-team-relay-plugin"`,
	},
	treeShaking: true,
	loader: {
		".png": "dataurl",
	},
	outfile: out + "/main.js",
});

const copyFile = (src, dest) => {
	if (src === dest) {
		return;
	}
	fs.copyFileSync(src, dest);
	console.log(`Copied ${src} to ${dest}`);
};

const watchAndMove = (fnames, mapping) => {
	// only usable on top level directory
	const watcher = chokidar.watch(fnames, {
		ignored: /(^|[/\\])\../, // ignore dotfiles
		persistent: true,
	});

	watcher.on("change", (filePath) => {
		const destName = mapping[filePath] || filePath;
		const destPath = path.join(out, path.basename(destName));
		copyFile(filePath, destPath);
	});
};

const mapping = debug ? { "manifest-beta.json": "manifest.json" } : {};
const manifest = debug ? "manifest-beta.json" : "manifest.json";
const files = ["styles.css", manifest];

const updateManifest = (manifest) => {
	const manifestPath = path.join(out, path.basename("manifest.json"));
	const raw_manifest = fs.readFileSync(manifestPath);
	const parsed = JSON.parse(raw_manifest);
	parsed.version = gitTag;
	const new_manifest = JSON.stringify(parsed, null, 2);
	console.log(`Set ${manifest} version to ${gitTag}`);
	fs.writeFileSync(manifestPath, new_manifest);
};

const move = (fnames, mapping) => {
	// only usable on top level directory
	mkdirSync(out, { recursive: true });
	for (const fname of fnames) {
		const destName = mapping[fname] || fname;
		const destPath = path.join(out, path.basename(destName));
		copyFile(fname, destPath);
	}
};

// Copy build output to Obsidian plugin directory
const copyToObsidian = () => {
	if (!obsidianPluginDir) return;
	if (!fs.existsSync(obsidianPluginDir)) {
		console.log(`Obsidian plugin dir not found: ${obsidianPluginDir}`);
		return;
	}
	const filesToCopy = ["main.js", "manifest.json", "styles.css"];
	for (const fname of filesToCopy) {
		const src = path.join(out, fname);
		const dest = path.join(obsidianPluginDir, fname);
		if (fs.existsSync(src)) {
			copyFile(src, dest);
		}
	}
	console.log(`Copied to Obsidian: ${obsidianPluginDir}`);
};

if (watch) {
	await context.watch();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	watchAndMove(files, mapping);
} else {
	await context.rebuild();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	process.exit(0);
}
