import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import { builtinModules as builtins } from "node:module";
import { execSync } from "child_process";
import chokidar from "chokidar";
import path from "path";
import fs, { mkdirSync } from "fs";
// Single source of truth for Svelte preprocessing, shared with svelte-check
// (see svelte.config.mjs). Two independent `sveltePreprocess()` calls could
// silently diverge -- svelte-check would then be type-checking a program
// preprocessed differently from what actually ships.
import svelteConfig from "./svelte.config.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// The version comes from the tag and is written into manifest.json below
// (updateManifest).
//
// `--always` USED to be here, and it cost us a public release. With no tag in
// reach the flag stops describe from failing and hands back a bare sha, which
// the build then silently writes into the manifest as the version. That is how
// "1.1.43-237-g1833d8a" -- the old repository's tag, the commit count above it
// and a hash -- shipped in this repository's first release. Nothing lied: the
// failure had been switched off in advance. Do not put the flag back.
// The Obsidian catalogue validator builds the published tarball, which carries
// no .git at all: there describe exits 128 and aborts the build at module load.
// That is a different case from "a git repository with no tag reachable" --
// failing there is correct and the strictness below is kept intact. When git is
// unavailable altogether the version comes from manifest.json, which the tarball
// already ships.
const gitTag = (() => {
	try {
		return execSync("git describe --tags", {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch (e) {
		// A git repository with no reachable tag must still fail, by design.
		if (fs.existsSync(".git")) throw e;
		return JSON.parse(fs.readFileSync("manifest.json", "utf8")).version;
	}
})();

// Second line of defence: describe can return a valid string of the wrong SHAPE.
// An allowlist, not a denylist -- we spell out what we accept, otherwise the next
// unexpected shape passes in silence (a bare sha is not caught by a suffix rule).
//
// Only release builds are checked: on a branch describe legitimately yields
// "0.0.1-5-gabc1234", and enforcing this on every build would turn main red on
// the very next commit after a tag -- a gate that blocks development gets
// removed rather than fixed.
const BARE_SEMVER = /^\d+\.\d+\.\d+$/;
if (process.env.CI_COMMIT_TAG && !BARE_SEMVER.test(gitTag)) {
	throw new Error(
		`refusing to build a release: version "${gitTag}" is not a bare semver. ` +
			"Tag the commit being released (git tag X.Y.Z) — the tag IS the version.",
	);
}

const develop = process.argv[2] === "develop";
const staging = process.argv[2] === "staging";
const watch = process.argv[2] === "watch" || staging;
const debug = process.argv[2] === "debug" || watch || staging || develop;
const out = process.argv[3] || ".";
const tld = staging ? "dev" : "md";

// Obsidian vault plugin directory for auto-copy on build
// Opt-in only. This used to hold one developer's personal vault path: a public
// repository carried it, and every build wrote into that machine.
const obsidianPluginDir = process.env.OBSIDIAN_PLUGIN_DIR || null;

// EVC Team Relay uses relay-onprem mode, no default System 3 URLs.
// (Relay health-check URL is NOT build-time config — it's derived at runtime
// from the relay-onprem settings' per-server controlPlaneUrl; see
// healthUrlForServer() in src/main.ts, TR-26.)
const apiUrl = "";
const authUrl = "";
console.log("git tag:", gitTag);

const NotifyPlugin = {
	name: "on-end",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) execSync(`notify-send "Build Failed"`);
		});
	},
};

const YjsInternalsPlugin = {
	name: "yjs-internals",
	setup(build) {
		build.onResolve({ filter: /^yjs\/dist\/src\/internals$/ }, args => {
			return {
				path: path.resolve("node_modules/yjs/src/internals.js"),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
        "moment",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: true },
			preprocess: svelteConfig.preprocess,
		}),
		YjsInternalsPlugin,
		NotifyPlugin,
	],
	target: "es2018",
	minify: !debug,
	logLevel: "info",
	sourcemap: debug ? "inline" : false,
	define: {
		BUILD_TYPE: debug ? '"debug"' : '"prod"',
		GIT_TAG: `"${gitTag}"`,
		API_URL: `"${apiUrl}"`,
		AUTH_URL: `"${authUrl}"`,
		REPOSITORY: `"entire-vc/evc-team-relay-plugin"`,
	},
	treeShaking: true,
	loader: {
		".png": "dataurl",
	},
	outfile: out + "/main.js",
});

const copyFile = (src, dest) => {
	if (src === dest) {
		return;
	}
	fs.copyFileSync(src, dest);
	console.log(`Copied ${src} to ${dest}`);
};

const watchAndMove = (fnames, mapping) => {
	// only usable on top level directory
	const watcher = chokidar.watch(fnames, {
		ignored: /(^|[/\\])\../, // ignore dotfiles
		persistent: true,
	});

	watcher.on("change", (filePath) => {
		const destName = mapping[filePath] || filePath;
		const destPath = path.join(out, path.basename(destName));
		copyFile(filePath, destPath);
	});
};

const mapping = debug ? { "manifest-beta.json": "manifest.json" } : {};
const manifest = debug ? "manifest-beta.json" : "manifest.json";
const files = ["styles.css", manifest];

const updateManifest = (manifest) => {
	const manifestPath = path.join(out, path.basename("manifest.json"));
	const raw_manifest = fs.readFileSync(manifestPath);
	const parsed = JSON.parse(raw_manifest);
	parsed.version = gitTag;
	const new_manifest = JSON.stringify(parsed, null, 2);
	console.log(`Set ${manifest} version to ${gitTag}`);
	fs.writeFileSync(manifestPath, new_manifest);
};

const move = (fnames, mapping) => {
	// only usable on top level directory
	mkdirSync(out, { recursive: true });
	for (const fname of fnames) {
		const destName = mapping[fname] || fname;
		const destPath = path.join(out, path.basename(destName));
		copyFile(fname, destPath);
	}
};

// Copy build output to Obsidian plugin directory
const copyToObsidian = () => {
	if (!obsidianPluginDir) return;
	if (!fs.existsSync(obsidianPluginDir)) {
		console.log(`Obsidian plugin dir not found: ${obsidianPluginDir}`);
		return;
	}
	const filesToCopy = ["main.js", "manifest.json", "styles.css"];
	for (const fname of filesToCopy) {
		const src = path.join(out, fname);
		const dest = path.join(obsidianPluginDir, fname);
		if (fs.existsSync(src)) {
			copyFile(src, dest);
		}
	}
	console.log(`Copied to Obsidian: ${obsidianPluginDir}`);
};

if (watch) {
	await context.watch();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	watchAndMove(files, mapping);
} else {
	await context.rebuild();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	process.exit(0);
}
